#!/bin/bash   

# Author: Gergely Száz <gergely.szaz@liferay.com>
# For updating a certain branch from liferay-portal-ee, typically:
#		master
#		ee-7.0.x
#		ee-6.2.x

CURRENT=$(branch)

if [ $# -eq 0 ]
then
	BRANCH=$CURRENT
else
	BRANCH=$1
fi

if [ $BRANCH == $CURRENT ]
  then
    echo "$BRANCH is in local repository"
    ACTION=pull
  else
	ACTION=fetch
fi

echo
echo "Updating $BRANCH"

git $ACTION upstream $BRANCH:$BRANCH  # does not actually merge changes, if it's not branch:branch
git push origin $BRANCH:$BRANCH