#!/bin/bash   

# Author: Gergely Száz <gergely.szaz@liferay.com>
# For updating a certain branch from liferay-portal-ee.
# Run from the repo folder without parameter to pull the current branch from upstream
# 	or add the branch name as a param to update any branch.

CURRENT=$(branch)

if [ $# -eq 0 ]
then
	BRANCH=$CURRENT
else
	BRANCH=$1
fi

if [ $BRANCH == $CURRENT ]
  then
    echo "$BRANCH is in local repository"
    ACTION=pull
  else
	ACTION=fetch
fi

echo
echo "Updating $BRANCH"

if [[ $ACTION = pull ]]
then
	git clean -fd
	git reset --hard
fi

git $ACTION upstream $BRANCH:$BRANCH  # does not actually merge changes, if it's not branch:branch
git push origin $BRANCH:$BRANCH